{% set version = "0.15.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metR/metR_{{ version }}.tar.gz
  sha256: e02a5a4acccfbe8531e891819cfe955676d2ede896bcd7bfeb2d41d4a5e9109f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-digest
    - r-formula
    - r-formula.tools
    - r-ggplot2 >=3.0.0
    - r-gtable
    - r-isoband
    - r-lubridate
    - r-memoise
    - r-plyr
    - r-purrr
    - r-scales
    - r-sf
    - r-stringr
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-digest
    - r-formula
    - r-formula.tools
    - r-ggplot2 >=3.0.0
    - r-gtable
    - r-isoband
    - r-lubridate
    - r-memoise
    - r-plyr
    - r-purrr
    - r-scales
    - r-sf
    - r-stringr

test:
  commands:
    - $R -e "library('metR')"           # [not win]
    - "\"%R%\" -e \"library('metR')\""  # [win]

about:
  home: https://github.com/eliocamp/metR
  license: GPL-3.0-only
  summary: Many useful functions and extensions for dealing with meteorological data in the tidy data framework. Extends 'ggplot2' for better plotting of scalar and vector fields and provides commonly used analysis methods in the atmospheric sciences.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - apcamargo
    - conda-forge/r
