{% set version = "0.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metR/metR_{{ version }}.tar.gz
  sha256: f8bfe5b25dd857b1a6d351c50c3d55e2ba2270e56c2300278d339e95fad33f53

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-matrix
    - r-rcurl
    - r-checkmate
    - r-curl
    - r-data.table
    - r-digest
    - r-dplyr
    - r-fields
    - r-formula.tools
    - r-ggplot2 >=3.0.0
    - r-gridextra
    - r-gtable
    - r-lubridate
    - r-maps
    - r-maptools
    - r-memoise
    - r-plyr
    - r-scales
    - r-sp
    - r-stringr
  run:
    - r-base
    - r-formula
    - r-matrix
    - r-rcurl
    - r-checkmate
    - r-curl
    - r-data.table
    - r-digest
    - r-dplyr
    - r-fields
    - r-formula.tools
    - r-ggplot2 >=3.0.0
    - r-gridextra
    - r-gtable
    - r-lubridate
    - r-maps
    - r-maptools
    - r-memoise
    - r-plyr
    - r-scales
    - r-sp
    - r-stringr

test:
  commands:
    - $R -e "library('metR')"           # [not win]
    - "\"%R%\" -e \"library('metR')\""  # [win]

about:
  home: https://github.com/eliocamp/metR
  license: GPL-3
  summary: Many useful functions and extensions for dealing with meteorological data in the tidy data framework. Extends 'ggplot2' for better plotting of scalar and vector fields and provides commonly used analysis methods in the atmospheric sciences.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - apcamargo
    - conda-forge/r

# Type: Package
# Package: metR
# Title: Tools for Easier Analysis of Meteorological Fields
# Version: 0.3.0
# Date: 2019-03-12
# Authors@R:  c(person(given = "Elio", family = "Campitelli", role = c("cre", "aut"), email = "elio.campitelli@cima.fcen.uba.ar", comment = c(ORCID = "0000-0002-7742-9230")))
# Description: Many useful functions and extensions for dealing with meteorological data in the tidy data framework. Extends 'ggplot2' for better plotting of scalar and vector fields and provides commonly used analysis methods in the atmospheric sciences.
# License: GPL-3
# URL: https://github.com/eliocamp/metR
# BugReports: https://github.com/eliocamp/metR/issues
# Depends: R (>= 2.10)
# Imports: checkmate, curl, data.table, digest, dplyr, fields, Formula, formula.tools, ggplot2 (>= 3.0.0), grid, gridExtra, gtable, lubridate, maps, maptools, Matrix, memoise, plyr, RCurl, scales, sp, stringr
# Suggests: covr, irlba, knitr, ncdf4, pkgdown, reshape2, rmarkdown, testthat, udunits2, vdiffr, viridis
# ByteCompile: yes
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-12 19:39:47 UTC; elio
# Author: Elio Campitelli [cre, aut] (<https://orcid.org/0000-0002-7742-9230>)
# Maintainer: Elio Campitelli <elio.campitelli@cima.fcen.uba.ar>
# Repository: CRAN
# Date/Publication: 2019-03-12 22:40:06 UTC
