appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: goI6oFh6kgjM6H9rcIyUoFGIZsDmE8WgyZcrU5he6gtPiSdqShi8FBR62rynbJDut3yoUcwl9FflhMKWoYqyQgif6m1g3JJgTbs4uQITUGyH+i2i9kZVuXohewU6sTvputFNStS0vpoLbOFo2A4zra9mho8XjYNmORTyP/P8GO63rWvXagmqixDKPY8zR/iApK/Ec2KmDUedHALcbhBXtonpzssxvHb1nNO/OWeIXnBkY2ox+QvTYvCxesZEhA1BukiWB1KfJLzfexgIXSORwsfUSsl43iiFzHdcdrmtZ3W+aLpGm1ryuFsyifXJrk1LV1idm8OVFaLb8oRIufBTAS1hrk+lM8LZdsjIKzpGmOuayrkROGV6vy+8ZrmSfOACopUVKER769vAuIS1cUr5mVgOoFjcBakRspYAGJXaVNWpuvBYXyWkpG5u697/9Yvvlqy/v3wosDwPT63KG8idRTn33Nj9x6oBGO+3Pp1nj1fRDuDST+vDpIIgGyT0pjZQ8D/HjFDhIar69+0M7m8zO6aP4EYKn1SaaUHwLSn7NM8NYOYB9KPiTKa2ZGtoQDMFMIRx/O2zyZo61+Il2cArFFtH8F4g0t969gASTH1bUG5hxeCAJZZdpYlwoXBXawqLAAzY1l7U3rF6VSND7z5mYo6hbgH+A8bdzGFQlgVLz/g=}
bot:
  automerge: true
